# Generated by Django 4.0.5 on 2022-07-08 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_alter_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvoters',
            field=models.ManyToManyField(related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
